### PR TITLE
wit, wit/bindgen: correctly generate linker names for world-level functions and interfaces

### LINKED ISSUE #175: wit/bindgen: mangled symbol generation for inline functions and interfaces in worlds is wrong
For the given WIT:

```wit
package issues:issue175;

world w {
	export example: interface {
		f1: func() -> s32;
		resource r {
			constructor(a: f64);
			get-a: func() -> f64;
			set-a: func(a: f64);
			add: static func(r: r, a: f64) -> r;
		}
	}
	export f2: func() -> s64;
}
```

- `wit-bindgen-go` generates `//go:wasmexport issues:issue170/w#f`
- `wit-bindgen` generates `__attribute__((__export_name__("f")))`

Implication: inline interfaces and functions imported into or exported from a world, are not package-qualified. `wit-bindgen-go` should be updated to reflect this.

### PR DESCRIPTION
**Pull request by ydnar**
Functions and interfaces imported into or exported directly from a world will now have the correct module name (`$root`).

For interfaces nested under a world, the generated Go package will be nested under the world’s package, e.g.:

```wit
package issues:issue175;

world w {
	export example: interface {
		f1: func() -> s32;
	}
	import f2: func() -> f32;
	export f3: func() -> s64;
}
```

Creates two Go packages:

1. `issues/issue175/w` exporting or importing functions with module `$root`
2. `issues/issue175/w/example` exporting or importing functions with module `example`

Fixes #175.

### CODE REVIEW

**Comment by Mossaka** [comment]
Do you want to merve PR #171 first so that we can run the full codegen tests against this PR?

**Comment by ydnar** [comment]
Done. I'll rebase

**Comment by ydnar** [comment]
I’ve verified the code this generates works in the TinyGo stdlib with `-target=wasip2`

File: wit/bindgen/generator.go [hunk 1]
```diff
@@ -47,8 +48,11 @@ type typeDecl struct {
 }
 
 type funcDecl struct {
-	f          function // The exported Go function
-	wasm       function // The wasmimport or wasmexport function
+	owner      wit.TypeOwner
+	dir        wit.Direction
+	f          *wit.Function
```
Comment (Mossaka) [inline wit/bindgen/generator.go:53]: suggest: add docs to describe what these fields do.

**Review by Mossaka — COMMENTED** [review]
Sorry for the late review. I left one comment for future reference,

File: wit/bindgen/generator.go (hunk 1 above)
Comment (ydnar) [reply wit/bindgen/generator.go:53]: Good idea. Will do
